FROM node:18 as base

FROM base as build
# Create app directory
WORKDIR /usr/local/apps/{{ appName }}

# Include node modules installed from app in the terminal
ENV PATH=/usr/local/apps/{{ appName }}/node_modules/.bin:$PATH

# Copy build Dependencies
COPY package*.json ./
COPY tsconfig.json ./

# Bundle App Source Code
COPY src ./src

# Install Dependencies
RUN npm install && npm cache clean --force
